"""empty message

Revision ID: 4cf6de55be5a
Revises: 
Create Date: 2020-05-17 12:15:22.709239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf6de55be5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('data_access', sa.String(length=300), nullable=True))
    op.add_column('sample', sa.Column('lab_head', sa.String(length=300), nullable=True))
    op.add_column('sample_version', sa.Column('data_access', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('sample_version', sa.Column('lab_head', sa.String(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_version', 'lab_head')
    op.drop_column('sample_version', 'data_access')
    op.drop_column('sample', 'lab_head')
    op.drop_column('sample', 'data_access')
    # ### end Alembic commands ###
